DashboardFinnhub/Models/Stock.cs
namespace DashboardFinnhub.Models
{
    public class Stock(string? symbol, double? c, double? h,
        double? l, double? o, double? pc, 
        string? country, string? siteUrl, 
        string? exchange, string? industry, 
        string? estimateCurrency, string? name)
    {
        public string? Symbol { get; } = symbol;
        public double? CurrentPrice { get; } = c;
        public double? HighPriceoftheDay { get; } = h;
        public double? LowPriceoftheDay { get; } = l;
        public double? OpenPriceoftheDay { get; } = o;
        public double? PreviousClosePrice { get; } = pc;
        public string? Country { get; } = country;
        public string? SiteURL { get; } = siteUrl;
        public string? Exchange { get; } = exchange;
        public string? Industry { get; } = industry;
        public string? EstimateCurrency { get; } = estimateCurrency;
        public string? Name { get; } = name;
    }
}

DashboardFinnhub/Components/TableStockInfoViewComponent.cs
using DashboardFinnhub.Models;
using Microsoft.AspNetCore.Mvc;

namespace DashboardFinnhub.Components
{
    [ViewComponent]
    public class TableStockInfoViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(Stock stock)
        {
            return View(stock);
        }
    }
}

DashboardFinnhub/Controllers/HomeController.cs
using DashboardFinnhub.Models;
using Microsoft.AspNetCore.Mvc;
using ServicesAbstractions;
using System.Globalization;

namespace DashboardFinnhub.Controllers
{
    public class HomeController(IFinnhubService finnhubService) : Controller
    {
        readonly IFinnhubService _finnhubService = finnhubService;
        [Route("/")]
        public async Task<IActionResult> Index([FromQuery] string symbol = "AAPL")
        {
            ViewBag.Title = "Home Page";
            var stocks = new List<Stock>();
            Dictionary<string, object>? stockQuote = await _finnhubService.GetStockPriceQuote(symbol);
            Dictionary<string, object>? stockInfoProfile = await _finnhubService.GetStockSymbolInfo(symbol);
            stockQuote!.Remove("d");
            stockQuote!.Remove("dp");
            stockQuote!.Remove("t");
            if (stockQuote!.ContainsKey("error") || stockQuote.All(item => TryParse(item.Value.ToString()) == 0d) || stockInfoProfile!.All(item => item.Value.ToString() == string.Empty))
            {
                return NotFound("The Stock Symbol cant be found");
            }
            double? c = TryParse(stockQuote?["c"]?.ToString());
            double? h = TryParse(stockQuote?["h"]?.ToString());
            double? l = TryParse(stockQuote?["l"]?.ToString());
            double? o = TryParse(stockQuote?["o"]?.ToString());
            double? pc = TryParse(stockQuote?["pc"]?.ToString());
            string? country = stockInfoProfile?["country"]?.ToString();
            string? siteUrl = stockInfoProfile?["weburl"]?.ToString();
            string? exchange = stockInfoProfile?["exchange"]?.ToString();
            string? industry = stockInfoProfile?["finnhubIndustry"]?.ToString();
            string? estimateCurrency = stockInfoProfile?["estimateCurrency"]?.ToString();
            string? name = stockInfoProfile?["name"]?.ToString();
            stocks.Add(new Stock(symbol.ToUpper(), c, h, l, o, pc, country, siteUrl, exchange, industry, estimateCurrency, name));

            return View(stocks);
        }

        private static double? TryParse(string? input)
        {
            if (input == null) return null;
            double result;
            var sucess = double.TryParse(input, CultureInfo.InvariantCulture, out result);
            return sucess ? result : null;
        }
    }
}

DashboardFinnhub/ViewComponents/TableStockFinnhubViewComponent.cs
using DashboardFinnhub.Models;
using Microsoft.AspNetCore.Mvc;

namespace DashboardFinnhub.ViewComponents
{
    [ViewComponent]
    public class TableStockFinnhubViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(Stock stock)
        {
            return View(stock);
        }
    }
}

DashboardFinnhub/Views/Home/Index.cshtml
@using DashboardFinnhub.Models
@model IEnumerable<Stock>

<div class="container-fluid">
    <h1 class="mt-4">Dashboard</h1>
    <div class="row">
        <div class="col-md-12">
            <div class="card mt-4">
                <div class="card-header">
                    Tabela de Cotações
                </div>
                <div class="card-body">
                    <table class="table table-striped text-center">
                        <thead>
                            <tr class="text-nowrap">
                                <th>Símbolo</th>
                                <th>Preço</th>
                                <th>Alta do Dia</th>
                                <th>Baixa do Dia</th>
                                <th>Abertura</th>
                                <th>Fechamento Anterior</th>
                                <th>País</th>
                                <th>Site URL</th>
                                <th>Plataforma</th>
                                <th>Indústria</th>
                                <th>Moeda Estimada</th>
                                <th>Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var stock in Model)
                            {
                                @await Component.InvokeAsync("TableStockFinnhub", stock)
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

DashboardFinnhub/Views/Shared/Components/TableStockFinnhub/Default.cshtml
@using DashboardFinnhub.Models
@using System.Globalization
@model Stock

<tr>
    <td>
        @Model.Symbol
    </td>
    <td class="text-center">
        <span class="fst-italic fw-bold">$</span>@if (Model.CurrentPrice is not null)
        {
            @Math.Round(Convert.ToDecimal(Model.CurrentPrice), 2)
        }
        else
        {
            <text>Can't get Current Price</text>
        }
    </td>
    <td>
        <span class="fst-italic fw-bold">$</span>@if (Model.HighPriceoftheDay is not null)
        {
            @Math.Round(Convert.ToDecimal(Model.HighPriceoftheDay), 2)
        }
        else
        {
            <text>Can't get High Price of the Day</text>
        }
    </td>
    <td>
        <span class="fst-italic fw-bold">$</span>@if (Model.LowPriceoftheDay is not null)
        {
            @Math.Round(Convert.ToDecimal(Model.LowPriceoftheDay), 2)
        }
        else
        {
            <text>Can't get Low Price of The Day</text>
        }
    </td>
    <td>
        <span class="fst-italic fw-bold">$</span>@if (Model.OpenPriceoftheDay is not null)
        {
            @Math.Round(Convert.ToDecimal(Model.OpenPriceoftheDay), 2)
        }
        else
        {
            <text>Can't get Open Price of the Day</text>
        }
    </td>
    <td>
        <span class="fst-italic fw-bold">$</span>@if (Model.PreviousClosePrice is not null)
        {
            @Math.Round(Convert.ToDecimal(Model.PreviousClosePrice), 2)
        }
        else
        {
            <text>Can't get Previous Close Price</text>
        }
    </td>
    <td>
        @if (Model.Country is not null)
        {
            @Model.Country
        }
        else
        {
            <text>Can't get Country</text>
        }
    </td>
    <td>
        @if (Model.SiteURL is not null)
        {
            <a href="@Model.SiteURL">@Model.SiteURL</a>
        }
        else
        {
            <text>Can't get Site URL</text>
        }
    </td>
    <td>
        @if (Model.Exchange is not null)
        {
            @Model.Exchange
        }
        else
        {
            <text>Can't get Exchange</text>
        }
    </td>
    <td>
        @if (Model.Industry is not null)
        {
            @Model.Industry
        }
        else
        {
            <text>Can't get Industry</text>
        }
    </td>
    <td>
        @if (Model.EstimateCurrency is not null)
        {
            @Model.EstimateCurrency
        }
        else
        {
            <text>Can't get Estimate Currency</text>
        }
    </td>
    <td>
        @if (Model.Name is not null)
        {
            @Model.Name
        }
        else
        {
            <text>Can't get Name</text>
        }
    </td>
</tr>

DashboardFinnhub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js" integrity="sha512-ykZ1QQr0Jy/4ZkvKuqWn4iF3lqPZyij9iRv6sGqLRdTPkY69YX6+7wvVGmsdBbiIfN/8OdsI7HABjvEok6ZopQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">Dashboard - With Finnhub</a>
            </div>
        </nav>
    </header>
    <div class="container-sm w-25 flex-column">
        <form id="form" class="form-inline justify-content-center">
            <label for="search" class="mb-3">Visite <a href="https://stockanalysis.com/stocks/">https://stockanalysis.com/stocks/</a> para saber mais!</label>
            <input class="form-control form-control-sm mr-sm-2 mb-3" id="search" type="search" required placeholder="Digite simbolos aqui" aria-label="Pesquisar">
            <button class="btn btn-outline-success btn-sm my-2 my-sm-0" type="submit">Pesquisar</button>
        </form>
    </div>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</body>
</html>
<script>
    document.getElementById('form').addEventListener('submit', function(event){
        event.preventDefault();
        var query = document.getElementById('search').value;
        window.location.href = '/?symbol=' + encodeURIComponent(query);
    })
</script>